Active Learning Classrooms: Research and Practical Applications

**Main idea**: Space impacts learning, and an intentional design of space can amplify the effects of active learning. 

- What is active learning
    - Bonwell/Eison
    - Lombardi "ecosystem" 
    - Some of the known benefits of AL (or just the Freeman 2014 study) 
- How can space impact active learning
    - Poll -- show a floorplan for a typical classroom and ask people to point out the potential issues 
    - Impeding movement
    - Rationing space 
    - Setting up assumptions about pedagogy and power
    - *Can* do active learning in these spaces but it's not the default and the space is working against you
- What is an ALC
    - Classroom 
    - Intentional design specifically intended to promote active learning: 
        - Flexible furniture 
        - Digital and analog tools 
        - Acentric/polycentric design
        - Facilitates *flexibility* and *flow* 
    - Examples: Labs, SCALE-UP, stuff from UBC
- What do we know about ALCs
    - ALCs have effects on traditional  metrics of academic success (Brooks & Solheim 2014)
    - ALC students compared with non-ALC students did not show the achievement gaps that were predicted to exist based on prior work (Brooks 2011)
    - Students doing active learnign in an ALC once a week with online meetings in between, did significantly better than students meeting in a traditional space 3x/week in person (Baepler,Walker,&Driessen,2014)
    - ALCs linked to significant improvements in student engagement and involvement along several axes (Scott-Weber) 
    - ALCs have similar effects on *instructors*: Brooks 2012: Significant movement in an ALC toward active learning even when specifically told not to change teaching style
    - Many related research findings -- see my paper 
- Bottom line: Space matters, and we can do intentional design of space to amplify active learning. 
- ALCs at GVSU
    - The past
        - Neimeyer/Honors College 
        - LIB 002 and JHZ 3068
    - The present
        - DCIH rooms 
        - DEV 121E
        - MAK A-1-111 and MAK B-1-110
    - The future? 
        - Expansion of ALCs
        - But what, where, how many, and who? 
